apiVersion: apps/v1
kind: Deployment
metadata:  
  name: go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: myapp
          image: myapp
          env:
          - name: DB_HOST
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: "21282908"
          - name: DB_NAME
            value: usersdb
          - name: DB_SSLMODE
            value: disable
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080